spring:
  datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@localhost:1521:ORCL
        username: demo
        password: demo
  jpa:
    hibernate:
       ddl-auto: update
       show-sql: true